backend:
  name: git-gateway
  branch: main # Adjust this if your main branch has a different name

media_folder: "static/uploads" # Folder in your repo where uploaded files will go
public_folder: "/uploads" # Folder in your published site where files will be served from

collections:
  - name: "updates"
    label: "Updates"
    folder: "content/updates"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - { label: "Image", name: "image", widget: "image" }
